AllCops:
  Exclude:
    - 'bundle_bin/*'
    - 'vendor/bundle/**/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

# 11/23/2019: To fix: Warning: unrecognized cop Style/Naming found in .rubocop.yml
#Style/Naming:
#  Exclude:
#    - exe/*

Style/RegexpLiteral:
  EnforcedStyle: mixed
